//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Forder
    {
        public int Oid { get; set; }
        public string Fname { get; set; }
        public int Qty { get; set; }
    }
}
